"""empty message

Revision ID: 339aa40b7132
Revises: None
Create Date: 2016-10-23 14:13:45.407400

"""

# revision identifiers, used by Alembic.
revision = '339aa40b7132'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vul_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vul_type_id', sa.Integer(), nullable=False),
    sa.Column('vul_name', sa.String(length=1024), nullable=False),
    sa.Column('vul_level', sa.Enum('high', 'medium', 'low'), nullable=False),
    sa.Column('vul_status', sa.Enum('resolved', 'unresolved'), nullable=False),
    sa.Column('vul_company', sa.String(length=100), nullable=False),
    sa.Column('vul_detail', sa.Text(), nullable=True),
    sa.Column('vul_find_date', sa.DateTime(), nullable=False),
    sa.Column('vul_solve_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vul_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vul_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vul_type')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vul_types')
    op.drop_table('vul_records')
    ### end Alembic commands ###
